services:
  app-db:
    image: mysql:8
    command: --character-set-server=utf8mb4
             --collation-server=utf8mb4_0900_bin
             --transaction-isolation=READ-COMMITTED
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - 53306:3306
    
  